name: Fix apt issues

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update and fix apt dependencies
      run: |
        sudo apt-get update
        sudo apt-get --fix-broken install -y
        sudo apt-get clean
        sudo apt-get install -y <package_name>
