name: Download Video Torrent and Send to Telegram

on:
  workflow_dispatch:
    inputs:
      magnet-link:
        description: 'Magnet link for the torrent'
        required: true
      telegram-bot-token:
        description: 'Telegram bot token'
        required: true
      telegram-channel-id:
        description: 'Telegram channel ID'
        required: true

jobs:
  download-video:
    runs-on: ubuntu-latest
    steps:

      # Étape 1: Installer aria2
      - name: Install aria2
        run: sudo apt-get install -y aria2

      # Étape 2: Télécharger la vidéo avec aria2c
      - name: Download Video with aria2c
        run: |
          magnet_link="${{ github.event.inputs.magnet-link }}"
          aria2c --seed-time=0 --dir=/tmp/video_download "$magnet_link"
          # Afficher les fichiers téléchargés
          echo "Downloaded files:"
          ls -l /tmp/video_download

      # Étape 3: Installer cURL
      - name: Install cURL
        run: sudo apt-get install -y curl

      # Étape 4: Vérifier l'existence de la vidéo et l'envoyer à Telegram
      - name: Check if video exists and send to Telegram
        run: |
          bot_token="${{ github.event.inputs.telegram-bot-token }}"
          channel_id="${{ github.event.inputs.telegram-channel-id }}"
          
          # Identifier la vidéo téléchargée
          video_file=$(ls /tmp/video_download | grep -E '\.mp4$' | head -n 1)

          if [ -z "$video_file" ]; then
            echo "No video file found in /tmp/video_download"
            exit 1
          fi

          # Afficher le chemin du fichier
          echo "Video found: /tmp/video_download/$video_file"

          # Envoi de la vidéo via Telegram
          curl -X POST "https://api.telegram.org/bot$bot_token/sendVideo" \
            -F chat_id="$channel_id" \
            -F video=@" /tmp/video_download/$video_file"
