name: Download Manga Torrent and Upload as Artifact

on:
  workflow_dispatch:
    inputs:
      magnet-link:
        description: 'Magnet link for the torrent'
        required: true
        default: 'magnet:?xt=urn:btih:...'  # Remplace avec un lien magnet par défaut si tu veux

jobs:
  download-torrent:
    runs-on: ubuntu-latest
    steps:

      # Étape 1: Installer aria2
      - name: Install aria2
        run: sudo apt-get install -y aria2

      # Étape 2: Télécharger le torrent avec aria2c
      - name: Download Torrent with aria2c
        run: |
          magnet_link="${{ github.event.inputs.magnet-link }}"
          aria2c --seed-time=0 --dir=/tmp/manga_download "$magnet_link"

      # Étape 3: Désactiver le seeding (aria2c arrête le seeding avec --seed-time=0)
      - name: Disable seeding after download
        run: |
          echo "Seeding is disabled by default with --seed-time=0 in aria2c"

      # Étape 4: Télécharger l'artefact pour 1 jour
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: downloaded-manga-torrent
          path: /tmp/manga_download/
          retention-days: 1
