name: Download Manga Torrent and Send to Telegram

on:
  workflow_dispatch:
    inputs:
      magnet-link:
        description: 'Magnet link for the torrent'
        required: true
      telegram-bot-token:
        description: 'Telegram bot token'
        required: true
      telegram-channel-id:
        description: 'Telegram channel ID'
        required: true

jobs:
  download-torrent:
    runs-on: ubuntu-latest
    steps:

      # Étape 1: Installer aria2
      - name: Install aria2
        run: sudo apt-get install -y aria2

      # Étape 2: Télécharger le torrent avec aria2c
      - name: Download Torrent with aria2c
        run: |
          magnet_link="${{ github.event.inputs.magnet-link }}"
          aria2c --seed-time=0 --dir=/tmp/manga_download "$magnet_link"

      # Étape 3: Installer cURL (pour envoyer le fichier via l'API Telegram)
      - name: Install cURL
        run: sudo apt-get install -y curl

      # Étape 4: Envoyer le fichier téléchargé à Telegram
      - name: Send the downloaded file to Telegram
        run: |
          bot_token="${{ github.event.inputs.telegram-bot-token }}"
          channel_id="${{ github.event.inputs.telegram-channel-id }}"
          file_path=$(ls /tmp/manga_download)

          # Vérifie que le fichier existe
          if [ -z "$file_path" ]; then
            echo "No file found in /tmp/manga_download"
            exit 1
          fi

          # Envoie le fichier via l'API Telegram
          curl -X POST "https://api.telegram.org/bot$bot_token/sendDocument" \
            -F chat_id="$channel_id" \
            -F document=@"$file_path"
