name: Send Telegram Photo

on:
  workflow_dispatch:
    inputs:
      bot_token:
        description: "Le Token de votre bot Telegram (fourni par BotFather)"
        required: true
      chat_id:
        description: "L'ID du canal ou groupe Telegram"
        required: true

jobs:
  sendPhoto:
    runs-on: ubuntu-latest

    steps:
    - name: Mise à jour du système
      run: |
        sudo apt-get update
        sudo apt-get --fix-broken install -y
        sudo apt-get install -y curl

    - name: Envoi d'une photo dans le canal Telegram
      env:
        TELEGRAM_BOT_TOKEN: ${{ github.event.inputs.bot_token }}
        TELEGRAM_CHAT_ID: ${{ github.event.inputs.chat_id }}
      run: |
        PHOTO_URL="https://en.wikipedia.org/wiki/File:Image_created_with_a_mobile_phone.png"  # Remplacez cette URL par celle de l'image que vous souhaitez envoyer
        curl -X POST \
          -H "Content-Type: multipart/form-data" \
          -F "chat_id=${TELEGRAM_CHAT_ID}" \
          -F "photo=${PHOTO_URL}" \
          "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendPhoto"
